dist: bionic
language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - coverage=no phpunit=^8.3
  matrix:
    - setup=basic
    - setup=stable
    - setup=lowest

before_install:
  - travis_retry composer self-update
  - composer config discard-changes true

before_script:
  - composer require "phpunit/phpunit=${phpunit}" --prefer-dist --no-interaction --no-update
  - if [[ ($setup = 'basic') || ($setup = 'coveralls') ]]; then travis_retry composer install --prefer-dist --no-interaction; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi
  - if [[ $setup = 'coveralls' ]]; then wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar; chmod +x php-coveralls.phar; fi

script:
  - if [[ $coverage = 'yes' ]]; then ./vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml; fi
  - if [[ $coverage = 'no' ]]; then ./vendor/bin/phpunit -c phpunit.xml --testdox --verbose; fi

after_script:
  - if [[ $setup = 'coveralls' ]]; then php-coveralls.phar -v; fi

matrix:
  include:
    - php: 7.3
      env: setup=basic phpunit=^9.0
    - php: 7.4
      env: setup=basic phpunit=^9.0
    - php: 7.3
      env: setup=stable phpunit=^9.0
    - php: 7.4
      env: setup=stable phpunit=^9.0
    - php: 7.3
      env: setup=lowest phpunit=^9.0
    - php: 7.4
      env: setup=lowest phpunit=^9.0
    - php: 8.0
      env: setup=stable phpunit=^9.0
    - php: 8.0
      env: setup=basic phpunit=^9.0
    - php: 8.0
      env: setup=lowest phpunit=^9.0
    - php: 7.2
      env: setup=coveralls coverage=yes
  allow_failures:
    - env: setup=coveralls coverage=yes
  fast_finish: true
